{% set name = "quantiphyse-qbold" %}
{% set version = "0.9.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/quantiphyse-qbold-{{ version }}.tar.gz
  sha256: fd6183f7e6a7ee7895199e0c4344ef85fe9c7a6c696fc473b5c3752df77b02a5

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - numpy
    - python >={{ python_min }}
    - quantiphyse-fabber

test:
  requires:
    - python {{ python_min }}
  imports:
    - quantiphyse_qbold

about:
  home: https://quantiphyse.readthedocs.io/
  summary: Quantiphyse plugin for qBOLD-MRI data
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mcraig-ibme
